export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOADING = "LOADING";
export const CURRENT_USER = "CURRENT_USER";

export const LOGIN_SUCCEED = "LOGIN_SUCCEED";
export const LOGOUT_SUCCEED = "LOGOUT_SUCCEED";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const ADD_LEVEL = "ADD_LEVEL";
export const FETCH_LEVELS_SUCCEED = "FETCH_LEVELS_SUCCEED";
export const FETCH_LEVELS_FAILED = "FETCH_LEVELS_FAILED";

export const ADD_SUBJECT = "ADD_SUBJECT";
export const FETCH_SUBJECT_SUCCEED = "FETCH_SUBJECT_SUCCEED";
export const FETCH_SUBJECT_FAILED = "FETCH_SUBJECT_FAILED";

export const ADD_SUBJECT_CONTENT = "ADD_SUBJECT_CONTENT";
export const FETCH_SUBJECT_CONTENT_SUCCEED = "FETCH_SUBJECT_CONTENT_SUCCEED";
export const FETCH_SUBJECT_CONTENT_FAILED = "FETCH_SUBJECT_CONTENT_FAILED";
